FROM php:8.4-cli-alpine

RUN apk add --no-cache \
    nodejs npm \
    git unzip curl \
    libpng-dev libjpeg-turbo-dev libwebp-dev \
    postgresql-dev \
    && docker-php-ext-install pdo pdo_pgsql opcache

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

COPY . .

RUN composer install --no-dev --no-interaction
RUN npm install
RUN npm run build

EXPOSE 8000
CMD ["sh", "-c", "php artisan migrate --force --seed && php artisan serve --host=0.0.0.0 --port=8000"]
